### ISSUE TITLE
https with wrong certificate

### ISSUE THREAD

**Issue by njordr** [stanfy/behave-rest#1]
Hi.

Great job, thanks.

Is it possible to connect to an https url without checking the certificate?

**Comment by onikiforov** [comment]
Added several possibilities to bypass certificate check:
1. Use step "I do not want to verify SSL certs" to disable checking for a whole suit
2. Use steps "I make an untrusted..." to disable verification for a specified request
3. Add `context.verify_ssl = False` to `environment.py` file to disable check for all tests

**Comment by onikiforov** [comment]
BTW, I checked this using "https://expired.badssl.com" site, so please let me know if it works for your case or not

**Comment by njordr** [comment]
It works also for me. Many thanks
