### ISSUE TITLE
Происхождение context.r

### ISSUE THREAD

**Issue by ghost** [stanfy/behave-rest#6]
Здравствуйте Олег!

Я работаю инженером по тестированию backend-а. Как начинающий автоматизатор тестирования, осваиваю Python3. 

Во первых, хочу поблагодарить вас за behave-rest - получился очень полезный инструмент для QA-инженера, постоянно используем в работе для тестировния api. :)

Так как я предпочитаю понимать как работает и что делает инструмент, которым пользуюсь, я начал разбираться в структуре фреймворка и сильно так завис на одном моменте. 

Вопрос такой: что такое context.r ? 

Если предназначение context в behave я понимаю, то происхождение  и назначение r поставило меня в тупик.

В behave_rest/steps/__init__.py неоднократно встречается context.r

Приведу пример:

@step('I want to reuse "{parameter_name}" parameter')
def store_parameter(context, parameter_name): data = context.r.json() 
return setattr(context, parameter_name, data[parameter_name])

context.r.json() подозрительно напоминает то, как мы присваеваем объект Responce (модуль requests) в переменную r:

r=requests.get("какой-нибудь урл"), где результат запроса из r потом распарсили в словарь с помощью json().

В дальнейшем, в файле также можно встретить конструкцию context.r. 

Связана ли она с модулем requests и если связана, то где во фреймворке behave-rest описано, что в r присваивается объект Responce?

Спасибо за внимание, буду очень рад если проясните ситуацию :)

**Comment by vixentael** [comment]
тегну @onikiforov просто чтобы убедиться, что Олег это видит :)

**Comment by onikiforov** [comment]
@cybskull 

Привет. Да, переменная r это действительно объект Response (я особо не заморачивался с названием :)

В степах которые связаны непосредственно с отправкой запроса:

('I make a {request_verb} request to "{url_path_segment}"'), 
('I make an untrusted {request_verb} request to "{url_path_segment}"')
('I make a {request_verb} request to "{url_path_segment}" with parameters')
('I make an untrusted {request_verb} request to "{url_path_segment}" with parameters')

мы сохраняем ответ в контекст (context.r), чтобы в дальнейшем иметь возможность использовать данные из ответа для проверок и манипуляций. Таким образом, напрмимер, вызов context.r.json() отдаст нам тело ответа в виде json'а, а context.r.status_code вернет статус код ответа.

**Comment by onikiforov** [comment]
@vixentael спасибо, мне на почту пришли нотифы ;)

**Comment by ghost** [comment]
@onikiforov, спасибо! 

Насколько я понимаю основная движуха происходит в строчке (взял из @given('I make an untrusted {request_verb} request to "{url_path_segment}"')):

**context.r = getattr(requests, request_verb.lower())(url, headers=context.headers, verify=context.verify_ssl)**,

и данная строка эквивалентна 
**context.r= requests.метод_запроса_взятый_из_context(тут url и header_name, тоже взятые из context)**

Т.е получается, что когда импортируем модуль в самом начале (import requests), мы получаем возможность обращаться к нему так, будто он находится в context? 

Я так решил, потому что в **getattr(requests, request_verb.lower())** мы запрашиваем атрибут request_verb( который в свою очередь мы точно берем из контекста) из объекта requests. 

А в log_full(context.r) просто отправляем результат запроса в функцию log_full, которая печатает красивый вывод.

**Comment by onikiforov** [comment]
@cybskull

> context.r = getattr(requests, request_verb.lower())(url, headers=context.headers, verify=context.verify_ssl),

> и данная строка эквивалентна
context.r= requests.метод_запроса_взятый_из_context(тут url и header_name, тоже взятые из context)

Верно. Это сделано для того чтобы не делать отдельный метод на каждый тип запроса.

> Т.е получается, что когда импортируем модуль в самом начале (import requests), мы получаем возможность обращаться к нему так, будто он находится в context?

Вот тут затрудняюсь точно сказать

> Я так решил, потому что в getattr(requests, request_verb.lower()) мы запрашиваем атрибут request_verb( который в свою очередь мы точно берем из контекста) из объекта requests.

Немного не так, через getattr мы вызываем метод requests который соответствует нашему request_verb, а сам request_verb берется из степа. Например для степа 'I make a {request_verb} request to "{url_path_segment}"' при записи 'I make a POST request...' вызовется requests.post. 

> А в log_full(context.r) просто отправляем результат запроса в функцию log_full, которая печатает красивый вывод.

Точно

**Comment by ghost** [comment]
Спасибо за объяснение
